var _tmr=_tmr||[];
(function(){function Fb(a){!ta&&"number"===typeof a&&(ta=a);return Y&&Gb&&cb?(db=[Gb-Y,cb-Y,Oa?Oa-Y:null,Pa?Pa-Y:null,ta?ta-Y:null].join("/"),Oa&&(Pa&&ta)&&(Fb=function(){return db}),db):null}function s(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function N(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}function Hb(a,b){try{if(a.nodeName.toLowerCase()===b.toLowerCase())return a;if(a.parentNode)return Hb(a.parentNode,b)}catch(c){n&&
console.warn("[TopMailRu] Error#1.25",c)}return null}function Ib(a,b){if(null===a.offsetParent||(0==a.offsetHeight||0==a.offsetWidth||0==a.clientHeight||0==a.clientWidth)||b&&(0==a.offsetLeft||0==a.offsetTop))return!1;if(void 0!==e.getComputedStyle){var c=e.getComputedStyle(a,null);return"none"!==c.display&&"hidden"!==c.visibility}return!0}function da(a,b){for(var c=0,d=b.length;c<d;c++)if(b[c]==a)return!0;return!1}function Z(a){var b=typeof a;return!("number"===b||"boolean"===b||"string"===b||a.nodeType||
a===a.window)}function ea(a){return"[object Array]"===Object.prototype.toString.call(a)}function qa(){var a=arguments,b=a[0]||{},c=!1,d=1,g=a.length,h,k,w,e,m;"boolean"===typeof b&&(c=b,b=a[d++]||{});for(Z(b)||(b={});d<g;d++)if(null!=(h=a[d]))for(k in h)w=b[k],e=h[k],b!==e&&(c&&e&&(Z(e)||(m=ea(e)))?(m?(m=!1,w=w&&ea(w)?w:[]):w=w&&Z(w)?w:{},b[k]=qa(c,w,e)):void 0!==e&&(b[k]=e));return b}function Jb(a,b,c){if(!a)return null;var d=a.match(b),g=2<arguments.length?c:0;return d&&d.length>g?d[g]:null}function Kb(a){return(""+
a).replace(/[\/\^\$\*\+\?\.\|\(\)\[\]\{\}\\]/g,"\\$&")}function eb(a){return Jb(a.host,/^(?:w{3}.)?(.*)$/,1)||""}function xc(a,b,c){a=eb(a);b=(b&&0<b?b:URL_HELPER__MASK_LEVEL)-1;var d=1;a=a.replace(RegExp("^.*(?:\\.((?:[^\\.]+\\.){"+b+"}[^\\.]+$))"),"$1");if(d=a.match(/\./g))d=d.length;a="(?:^|\\.{"+(b-d+1)+"})"+Kb(a)+"$";return RegExp(c?"^((?!"+a+").)*$":a)}function fb(a){var b;if(ea(a)){b=[];for(var c=0,d=a.length;c<d;c++)b.push(fb(a[c]));return b}b=a instanceof RegExp?a:RegExp("^"+Kb(a)+"$");return b.test(eb(x))?
null:b}function Lb(a){var b="";try{var c=new Uint8Array(a);e.crypto.getRandomValues(c);for(var d=0;d<a;d++)b+=(c[d]%16).toString(16)}catch(g){b="";for(d=0;d<a;d++)c=Math.floor(16*Math.random()),b+=c.toString(16)}return b}function y(){return(new Date).getTime()}function J(a,b){var c={data:b,raw:a,url:gb(a)},d;if(!yc||"function"!==typeof navigator.sendBeacon)d=!1;else{c.dataSplitter=";";var g=hb(c.data,c.dataSplitter);try{d=!0===navigator.sendBeacon(c.url,g)}catch(h){d=!1}}d||(void 0===b?(c.dataSplitter=
";",c.open=zc,c.connect=Ac,c.startListen=Bc,c.stopListen=Cc,c.open(c),c.connect(c)):("function"===typeof e.XMLHttpRequest?(c.dataSplitter=";",c.open=Dc,c.connect=Ec,c.startListen=Fc,c.stopListen=Gc,c.open(c),c.connect(c),d=!0):d=!1,d||Hc(c)))}function Hc(a){var b=f.createElement("iframe"),c=f.createElement("div");c.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");c.appendChild(b);f.body.appendChild(c);
try{var d=b.contentWindow.document,g=d.createElement("div"),h;for(h in a.data)if(a.data.hasOwnProperty(h)){var k=a.data[h],e=typeof k;if("string"===e||"number"===e){var Q=d.createElement("input");Q.setAttribute("type","hidden");Q.setAttribute("name",h);Q.value=k;g.appendChild(Q)}}var m=d.createElement("form");m.setAttribute("action",a.url);m.setAttribute("method",Mb);m.setAttribute("enctype",Nb);m.appendChild(g);var Ob=d.createElement("div");Ob.appendChild(m);d.body.appendChild(Ob);var v=function(){try{N(b,
"load",v),f.body.removeChild(c)}catch(a){n&&console.warn("[TopMailRu] Error#1.2",a)}};s(b,"load",v);m.submit()}catch(l){n&&console.warn("[TopMailRu] Error#1.3",l)}}function Dc(a){a._connection=new e.XMLHttpRequest}function Ec(a){a._connection.open(Mb,a.url);a._connection.setRequestHeader("Content-Type",Nb);a._connection.send(hb(a.data,a.dataSplitter))}function Fc(a){s(a._connection,"load",a._onload);s(a._connection,"error",a._onerror)}function Gc(a){N(a._connection,"load",a._onload);N(a._connection,
"error",a._onerror)}function zc(a){a._connection=new Image}function Ac(a){a._connection.src=a.url+hb(a.data,a.dataSplitter)}function Bc(a){a._connection.onload=a._onload;a._connection.onerror=a._onerror}function Cc(a){a._connection.onload=null;a._connection.onerror=null}function hb(a,b){var c=b||";",d="",g;for(g in a)if(a.hasOwnProperty(g)){var h=a[g],k=typeof h;if("string"===k||"number"===k)d+=c+escape(g)+"="+escape(h)}return d}function gb(a){a="string"===typeof a?a:"/";return"https://top-fwz1.mail.ru"+
("/"===a.substring(0,1)?"":"/")+a}function $(a){return(a=f.cookie.match(RegExp("(?:^|; )"+a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)")))?decodeURIComponent(a[1]):null}function ua(a,b,c){c=c||{};var d=c.expires;"number"===typeof c.expires&&(d=new Date,d.setTime(d.getTime()+c.expires));d&&d.toUTCString&&(d=d.toUTCString());c.expires=d;a=a+"="+encodeURIComponent(b);for(var g in c)if((b=c[g])||0===b)a+="; "+g,!0!==b&&(a+="="+b);f.cookie=a}function ib(a,b){var c=b||{};c.expires=-1;ua(a,
"",c)}function Ic(){var a="tmr"+(""+Math.random()).slice(2);try{return la=e.localStorage||null,la.setItem(a,a),la.removeItem(a),!0}catch(b){return la=null,n&&console.warn("[TopMailRu] Error#1.4",b),!1}}function za(a){try{return la.getItem(a)}catch(b){n&&console.warn("[TopMailRu] Error#1.5",b)}return null}function Aa(a,b){try{la.setItem(a,b)}catch(c){n&&console.warn("[TopMailRu] Error#1.6",c)}}function Jc(){if(!ma)return null;for(var a=x.hostname.split(".").reverse(),b,c=1,d=a.length;c<d;c++){b=a[0];
for(var g=1;g<=c;g++)b=a[g]+"."+b;var g=""+y(),h={domain:b,path:"/",expires:3E5};try{ua("tmr_tcdhn",g,h);var k=$("tmr_tcdhn");ib("tmr_tcdhn",h);if(k===g)return b}catch(e){n&&console.warn("[TopMailRu] Error#1.8",e)}}return null}function Pb(a,b){ma&&ua(a,b,jb);na&&Aa(a,b)}function kb(a,b,c){var d=f.createElement("script");d.type="text/javascript";d.async=!0;b&&(d.onload=b);c&&(d.onerror=c);d.src=a;document.body.appendChild(d)}function Qb(a){var b=";e="+escape("detect");J(M(a,K,!1,!1)+b)}function Rb(a,
b){if(a.length&&null!==b.ecom_data){var c=xa(b.ecom_data),c=c?(""+c).substring(1,c.length-1):"";if(!(4096<c.length||-1===c.search(/\S/))){var d=lb("_m",b.ecom_method),g=lb("_t",b.ecom_type),h=lb("_jst",Sb()),c="{"+c+d+g+h+"}";J(M({id:a[0]},Kc,!1,!0)+(";ids="+escape(a.join()))+(";e="+escape(c)))}}}function lb(a,b){var c=',"'+a+'":';if(!b||!b.length)return c+"[]";try{return c+'["'+b.join('","')+'"]'}catch(d){}return c+"false"}function Lc(){var a=$(Tb);if(null===a)return null;a=a.split("|");if(3!==a.length)return null;
var b=a[2],b=y()-b;return 0>b||b>Ub?null:{id:a[0],version:a[1]}}function Vb(a){mb=!0;a.length&&kb(gb("/js/dyn-goal-config.js?ids="+a.join(",")))}function l(){}function va(a){a&&"object"===typeof a&&(!aa&&"id"in a)&&(aa=a.id)}function Ba(a){return!Qa?void 0:Qa[a]}function Mc(a){return(a=Ba(a))&&Ra?a-Ra:void 0}function Wb(){if(Qa){for(var a=0,b="domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),c=0;c<b.length;c++){var d=Ba(b[c]);if(0<
d&&(d<a||0==a))a=d}return a?a:void 0}}function O(a,b){var c=1<arguments.length?b:aa;return a&&"object"===typeof a&&("id"in a&&a.id||c)}function Xb(a,b,c,d){var g=parseInt(a,10);return isNaN(g)||""+g!==""+a||g<b||g>c?d||0===d?d:null:g}function Yb(a,b){if("URL"in window){var c=b;try{c=new URL(a)}catch(d){return b}return c?a:b}return a||b}function Zb(a,b){if("URL"in window){var c=b;try{c=new URL(a)}catch(d){return"d:"}return c?"e:":"d:"}return a?"e:":"d:"}function $b(a,b,c){if(!a)return b;if("URL"in
window){try{var d=new URL(a);if(d)return a}catch(g){}try{if(d=new URL(a,c))return d.href?d.href:d.toString()}catch(h){}return b}return a}function ac(a,b,c){if(!a)return"d:";if("URL"in window){try{var d=new URL(a);if(d)return"e:"}catch(g){}try{if(d=new URL(a,c))return"h:"}catch(h){}return"d:"}return"e:"}function M(a,b,c,d){na&&Aa(Ca,++H);var g="id"in a?a.id:aa,h=Yb(a.url,x.href),k=Yb(a.referrer,f.referrer),w=$b(a.url,x.href,x.href),Q=$b(a.referrer,f.referrer),m="title"in a?a.title:f.title,l;l=nb;null===
l&&(l=Nc());l=null!==l?l?1:0:null;var v="userid"in a?a.userid:U||0===U?U:void 0,t=ra?ra:void 0,p;p=oa&&a.bfCache;var q="pageView"===a.type&&a.timespent,u=[];aa&&g!==aa&&u.push("sec");"dataLayer"in e&&u.push("dl");P&&u.push(["ecom"].concat(P).join("-"));var Da=Oc();Da&&Da.length&&u.push(["jst"].concat(Da).join("-"));p&&u.push("bfc");R&&q&&u.push("ts");e.top!==e&&u.push("frame");(!0===B.webdriver||f.$cdc_asdjflasutopfhvcZLmcfl_)&&u.push("wda");p=u.join(",");q=(new Date).getTimezoneOffset();u="";if(e.Intl)try{u=
e.Intl.DateTimeFormat().resolvedOptions().timeZone||""}catch(Pc){n&&console.warn("[TopMailRu] Error#1.1",Pc)}Da=q+"/"+u;q=bc;q=null!==q?q:Lc();u=Fb(a.start);b=b+"?_="+Math.random()+(g?";id="+escape(g):"")+(w?";u="+escape(w):"")+(Q?";r="+escape(Q):"")+(h!==w?";u2="+Zb(a.url,x.href)+ac(a.url,x.href,x.href):"")+(k!==Q?";r2="+Zb(a.referrer,f.referrer)+ac(a.referrer,f.referrer):"");g=Xb(a.gender,1,2);b+=null!==g?";gender="+g:"";g=Xb(a.age,1,127);d=b+(null!==g?";age="+g:"")+("pid"in a?";pid="+escape(a.pid):
"")+(void 0!==v?";userid="+escape(v):"")+(void 0!==t?";uparams="+escape(xa(t)):"")+(d&&m?";title="+encodeURIComponent(m):"");m=";s="+Qc+";vp=";t=v=0;f.documentElement&&(f.documentElement.clientWidth||f.documentElement.clientHeight)?(v=f.documentElement.clientWidth,t=f.documentElement.clientHeight):"number"==typeof e.innerWidth&&(v=e.innerWidth,t=e.innerHeight);d=d+(m+(""+v+"*"+t)+";touch="+Rc+";hds="+Sc)+";sid="+ob+";ver="+Tc+";tz="+encodeURIComponent(Da)+";st="+Wb();if(c){if(!Qa||!pb)c="";else{c=
[];c.push(pb.type);c.push(pb.redirectCount);c.push(Ra);for(m=0;m<cc.length;m++)c.push(Mc(cc[m]));c=c.join("/")}c=";nt="+c}else c="";c=d+c+(u?";ct="+u:"")+(Sa?";gl="+Sa:"")+("device"in a?";device="+escape(a.device):"")+";ni=";if(!B||!B.connection)u="";else{u=B.connection;d=[];for(v=0;v<dc.length;v++){m=u[dc[v]];if(void 0!==m)switch(m){case !0:m=1;break;case !1:m=0;break;default:m=(""+m).replace(/\//g,"_")}d.push(m)}u=d.join("/")}return c+u+("params"in a?";params="+escape(xa(a.params)):"")+(null!==
l?";detect="+l:"")+(ma||na?";lvid="+escape([Ea,y(),H,fa].join(":")):"")+(p?";opts="+escape(p):"")+(q?";flocid="+escape(q.id)+";flocv="+escape(q.version):"")+(ec&&Fa?";fpid="+Fa:"")+("version"in a?";appver="+escape(a.version):"")+(ga.support?";visible="+ga.getValue():"")+";js=13"}function qb(a){a=";e="+escape(a);for(var b=0;b<C.length;b++)J(M(C[b],K,!1,!0)+a)}function Uc(){nb=!0;fc(1);if(!rb&&!Ga){Ga=!0;for(var a=0;a<C.length;a++)Qb(C[a])}}function Vc(){fc(0);nb=!1}function Nc(){var a=$(gc);if(null===
a)return null;a=a.split("|");if(2!==a.length)return null;var b=a[1],b=y()-b;if(0>b||b>hc)return null;a=parseInt(a[0],10);return isNaN(a)?null:a}function fc(a){var b=y();a=[a,b].join("|");ua(gc,a,{path:"/",expires:hc})}function Wc(){var a=0;Ta&&(a=y()-Ta);Xc||(D.dcl3=setTimeout(function(){qb("DCL/3")},Math.max(3E3-a,0)))}function Yc(){var a=0;Ua&&(a=y()-Ua);Zc||(D.pvt2=setTimeout(function(){qb("PVT/2")},Math.max(2E3-a,0)));$c||(D.pvt15=setTimeout(function(){qb("PVT/15")},Math.max(15E3-a,0)))}function ic(){sb||
setInterval(function(){_tmr.beat()},6E4)}function ad(a,b,c,d){if(!b||!d||d===tb&&b===tb&&c===tb)return null;b={goal:bd+b,value:c||0,params:{product_id:d}};a&&(b.id=a);return b}function Va(){Ta=y();f.addEventListener?(N(f,"DOMContentLoaded",Va),_tmr.onready()):f.attachEvent&&"complete"===f.readyState&&(N(f,"readystatechange",Va),_tmr.onready());jc()}function ub(a){Ua=y();if(oa){if(a.persisted){Ha=Ia=Wa=0;vb=wb=!1;R&&z.launch();a=xb;xb=[];for(var b=0,c=a.length;b<c;b++)_tmr.callbackOnReady(a[b]);a=
Xa;Xa={};for(b in a)_tmr.pageView(a[b]);ic()}}else N(e,"load",ub);_tmr.onready();_tmr.onload()}function Ja(){oa||(N(e,"unload",Ja),N(e,"beforeunload",Ja));_tmr.unload()}function jc(){R&&z.launch();if(cd&&kc){window.addEventListener("message",function(a){var c=null;try{if(c=a.data,Z(c)||(c=Ya(c)),"LOAD_BUTTONS_SCRIPT"===c.type){var d;var g=document.referrer;a=null;var h=(""+c.lang).toLowerCase(),k;b:{for(var c=0,e=yb.length;c<e;c++)if(yb[c]===h){k=!0;break b}k=!1}k||(h=yb[0]);try{a=(new URL(g)).host}catch(f){}d=
a&&dd.test(a)?"https://"+a+"/top_constructor/buttons_"+h+".js":gb("/js/dyn-goal-wizard-"+h+".js");kb(d)}}catch(m){}});if(window.opener)try{window.opener.postMessage({type:"READY"},document.referrer)}catch(a){}mb||(Za.push.apply(Za,Ka),Vb(Ka))}}if("[object Array]"===Object.prototype.toString.call(_tmr)){var Gb=(new Date).getTime(),cb=null,Oa=null,Pa=null,ta=null,Y=null,db=null,K="/tracker",Kc="/datalayer",e=window,B=navigator,f=document,x=location,ba="string"===typeof x.hostname?x.hostname:"",La=-1!=
ba.search(/(^|\.)odnoklassniki\.ru$/)||-1!=ba.search(/(^|\.)ok\.ru$/),lc=-1!=ba.search(/(^|\.)vk\.com$/);ba.search(/(^|\.)mail\.ru$/);var ed=-1!=ba.search(/(^|\.)lamoda\.ru$/),fd=-1!=ba.search(/(^|\.)kommersant\.ru$/);ba.search(/(^|\.)top\.mail\.ru$/);ba.search(/(^|\.)dzen\.ru$/);var mc="string"===typeof x.search&&-1!=x.search.search(/[?&]rb_clickid=/),n="string"===typeof x.search&&-1!=x.search.search(/[?&]tmr_debug=1(?:&|$)/),yc=!1,sb=La||lc||ed||fd,Zc=!mc,$c=La,Xc=!mc,rb=!1,R=e.performance&&"visibilityState"in
f,gd=[36383],hd=!(La||lc),cd=!0,ec=!0,nc=e.JSON&&e.JSON.stringify&&e.JSON.parse,oa="onpageshow"in e&&"onpagehide"in e,kc="URL"in e,xa=nc?e.JSON.stringify.bind(e.JSON):function(a){return""},Ya=nc?e.JSON.parse.bind(e.JSON):function(a){return{}},yb=["ru","en"],dd=/^(ads\d+\.my\.com)$/,Mb="POST",Nb="application/x-www-form-urlencoded",ma=!(0===x.hostname.search(/^(\d+.)+\d+$/g)||-1!==x.hostname.search(/:/g)),la=null,na=Ic(),jb={domain:Jc(),path:"/",expires:287712E5};(function(){var a;if(a=f.cookie.match(RegExp("(?:^|; )(tmr_tcdhn\\d+)=([^;]*)",
"g"))){for(var b=[],c,d=0,g=a.length;d<g;d++)c=a[d],(c=c.match(/(?:^|; )(tmr_tcdhn\d+)=([^;]*)/))&&b.push(c.slice(1));a=b}else a=null;if(a){d=0;for(g=a.length;d<g;d++)b=a[d][0],ib(b,jb)}})();var Ga=!1,nb=null,hc=864E5,gc="tmr_detect",id=function(){function a(a,b){for(var c=a.length,k,e,f=0;f<b;f++)e=Math.floor(Math.random()*c),k=a[f],a[f]=a[e],a[e]=k;return a.slice(0,b)}function b(b,g){var h=f.createElement("div"),e=String.fromCharCode(97,100,118,98,108,111,99,107,32,97,100,118,101,114,116,98,108,
111,99,107,32,97,100,118,101,114,116,66,108,111,99,107,32,98,45,114,98,32,98,97,110,110,101,114,95,50,52,48,32,112,45,116,97,114,103,101,116,32,112,117,98,95,51,48,48,120,50,53,48,32,112,117,98,95,51,48,48,120,50,53,48,109,32,112,117,98,95,55,50,56,120,57,48,32,114,98,95,98,111,100,121,32,114,98,45,102,108,111,97,116,105,110,103,32,114,98,45,115,108,111,116,32,114,98,45,118,105,100,101,111,45,119,105,100,103,101,116,32,116,101,120,116,45,97,100,32,116,101,120,116,45,97,100,45,108,105,110,107,115,
32,116,101,120,116,45,97,100,115,32,116,101,120,116,45,98,97,110,110,101,114,32,116,101,120,116,95,97,100,32,116,101,120,116,95,97,100,115,32,116,101,120,116,65,100,32,116,101,120,116,97,100,32,116,101,120,116,65,100,115,32,116,101,120,116,97,100,115,32,116,103,98,45,98,97,110,110,101,114,32,116,114,103,45,98,45,98,97,110,110,101,114,45,98,108,111,99,107).split(" "),e=a(e,c);h.setAttribute("class",e.join(" "));h.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");
h.setAttribute("id","trg-b-banners-1");h.setAttribute("data-view","SlotView.mimic");this.bait=f.body.appendChild(h);this.bait.offsetParent;this.bait.offsetHeight;this.bait.offsetLeft;this.bait.offsetTop;this.bait.offsetWidth;this.bait.clientHeight;this.bait.clientWidth;this.loopNumber=0;this.fnPositive=b||null;this.fnNegative=g||null;var w=this;setTimeout(function(){w._checkBait.call(w)},1)}var c=7;b.prototype._checkBait=function(){if(Ga)this._stop();else{var a=null!==f.body.getAttribute("abp")||
!Ib(this.bait,!0);(!0===a||10<=++this.loopNumber)&&this._stop();var b;if(a&&this.fnPositive)try{b=this.fnPositive,b()}catch(c){n&&console.warn("[TopMailRu] Error#1.9",c)}else if(!a&&10>this.loopNumber){var e=this;setTimeout(function(){e._checkBait.call(e)},50*this.loopNumber)}else try{b=this.fnNegative,b()}catch(w){n&&console.warn("[TopMailRu] Error#1.10",w)}}};b.prototype._stop=function(){try{f.body.removeChild(this.bait)}catch(a){n&&console.warn("[TopMailRu] Error#1.11",a)}};return function(a,c){new b(a,
c)}}(),P=null,oc="ecommerce",V="dataLayer",ha=null,zb=!1,$a=[],jd=[36383,2540645,3171181,3074137,2057653],kd=[],Ab;(function(){function a(a,b){for(var c=0,d=b.length;c<d;c++)-1===a.indexOf(b[c])&&a.push(b[c])}function b(b,c,d){for(var g={ecom_method:[],ecom_type:[],ecom_data:{events:[]}},h=0,e=b.length;h<e;h++){var k=q[b[h]];if(k){a(g.ecom_method,[b[h]]);for(var m=0,f=k.length;m<f;m++)for(var w=0,Q=d.length;w<Q;w++){var l=k[m][d[w]];if(l)for(var r=0,n=c.length;r<n;r++)if(-1!==k[m].type.indexOf(c[r])){a(g.ecom_type,
[c[r]]);a(g.ecom_data.events,l);break}}}}return g}function c(a,b,c){if(!a||!c||!(b in q))return null;for(var d,g=0,h=q[b].length;g<h;g++)if(d=q[b][g],c in d&&-1!==d[c].indexOf(a))return{ecom_method:[b],ecom_type:d.type.slice(),ecom_data:{}};return null}function d(a){for(var d=[],e,k,l=0,ld=a.length;l<ld;l++)if(k=a[l]){e=null;try{if(k.ecommerce)e=g(k)||h(k);else if(null===k.ecommerce)e=null;else if(k.event){var pc={event:k.event,ecommerce:{}};e=g(pc)||h(pc)}else if("event"===k[0]){var qc=k[1],v=k[2],
A=c(qc,Q,t);A&&(A.ecom_data[qc]=v);e=A}else if(k.event===oc)a:{for(var E=b([f],[m],[p]),G=0,r=E.ecom_data.events.length;G<r;G++)if(!k.hasOwnProperty(E.ecom_data.events[G])){e=null;break a}delete E.ecom_data.events;E.ecom_data[oc]=k;e=E}}catch(q){n&&console.warn("[TopMailRu] Error#1.23",q),e=null}e&&(d.push(e),$a.push(e))}if(d.length){a=0;for(e=d.length;a<e;a++)Rb(ab,d[a]);P||(P=[0,0,V]);P[0]+=d.length;e=a=0;for(l=d.length;e<l;e++)a+=xa(d[e].ecom_data).length;P[1]+=a}}function g(a){var b,d;for(d in a.ecommerce)if(a.ecommerce.hasOwnProperty(d)&&
(b=c(d,f,l))){if(a.event&&(d=c(a.event,f,v)))for(var e=0,g=b.ecom_type.length;e<g;e++)-1===d.ecom_type.indexOf(b.ecom_type[e])&&(b.ecom_type.splice(e,1),g--,e--);b.ecom_data=a.ecommerce;return b}return null}function h(a){var b=a.event,d=c(b,f,v);d&&(d.ecom_data[b]=a.ecommerce);return d}function k(a){if((a=e[a])&&"function"===typeof a.push)d(a),ha=a.push,a.push=function(){var a=ha.apply(this,arguments);d([].slice.call(arguments,0));return a}}var f="push",Q="gtag",m="gse",l="inner",v="outer",t="external",
p="required",q={};q[Q]=[{type:["gee"],external:"add checkout checkout_option checkout_progress click detail promo_click remove select_content set_checkout_option view_refund".split(" ")},{type:["ga4"],external:"earn_virtual_currency join_group level_end level_start level_up post_score select_content spend_virtual_currency tutorial_begin tutorial_complete unlock_achievement ad_impression login search share sign_up add_payment_info add_shipping_info add_to_wishlist generate_lead select_item select_promotion view_cart view_item_list".split(" ")},
{type:["gee","ga4"],external:"add_to_cart begin_checkout purchase refund remove_from_cart view_item view_promotion".split(" ")}];q[f]=[{type:[m],required:["transactionId","transactionTotal"]},{type:["ga4"],outer:b([Q],["ga4"],[t]).ecom_data.events},{type:["gee"],inner:"click checkout checkout_option impressions promoClick promoView refund".split(" "),outer:"addToCart checkout checkoutOption productClick productDetail ProductImpressions promotionClick promotionView removeFromCart transactionPush".split(" ")},
{type:["ym","gee"],inner:["add","detail","purchase","remove"]},{type:["mt"],outer:["mt_order","mt_refund"]}];Ab=function(a){if(!(a===V&&ha)){a!==V&&($a=[]);var b=e[V];b&&"function"===typeof b.push&&ha&&(b.push=ha,ha=null);k(a);zb=!0}}})();var Sb=function(){var a=[{id:"gtag",globalVars:["google_tag_manager"]},{id:"ga",globalVars:["GoogleAnalyticsObject"]},{id:"ym",globalVars:["Ya",{re:"yaCounter\\d+"}]},{id:"vk",globalVars:["VK"]},{id:"vk",globalVars:["vkAsyncInit"]}],b={};return function(){var c;
try{c=Object.keys(e).join(",")}catch(d){c=null}for(var g=[],h,k=0,f=a.length;k<f;k++){h=b[a[k].id];if(void 0===h)a:{h=a[k].globalVars;for(var l=c,m=0,n=h.length;m<n;m++){var v=h[m];if("string"===typeof v&&!(v in e)||"string"===typeof v.re&&(l&&-1===l.search(RegExp("($|,)"+v.re+"(,|^)","m"))||1===n)){h=!1;break a}}h=!0}h&&(b[a[k].id]=!0,da(a[k].id,g)||g.push(a[k].id))}return g}}(),Oc=Sb,Ub=864E5,Tb="tmr_floc",bc=null;(function(a){try{f.interestCohort&&"function"===typeof f.interestCohort&&f.interestCohort().then(function(a){bc=
{id:a.id,version:a.version};a=[a.id,a.version];var b=y();a=a.concat(b).join("|");ua(Tb,a,{path:"/",expires:Ub})},function(){})}catch(b){}})();var Bb=!1,Sa=null,Ma=null,Cb=!1,rc;(function(){function a(a){try{var c=a.state;Ma=c in k?k[c]:h;Cb=c===e;Bb&&b(Cb)}catch(d){}}function b(a){try{a?(B[d].getCurrentPosition(c),f||(f=B[d].watchPosition(c))):(f&&B[d].clearWatch(f),c(null))}catch(b){}}function c(a){if(a)try{var b=a.coords,b=[b.latitude,b.longitude,b.accuracy,b.altitude,b.altitudeAccuracy,b.heading,
b.speed];a=0;for(var c=b.length;a<c;a++)"number"!==typeof b[a]&&(b[a]="");b.splice(0,0,Ma);Sa=b.join("/")}catch(d){}else Sa=Ma}var d="geolocation",e="granted",h="u",k={denied:"d"};k[e]="g";k.prompt="p";var f=null;(function(){Ma=h;c(null);try{d in B?B.permissions&&B.permissions.query({name:d}).then(function(b){a(b);b.onchange=function(){a(b)}}):Ma="n"}catch(b){}})();rc=b})();var ga={support:!1},ga=function(){function a(){g(k)}function b(){g(k,t)}function c(a){a.persisted&&(p[k]=null,p[l]=null,g(k,
x))}function d(){return n?!f[n]:null}function g(a,b){var c=y(),e="undefined"===typeof b?d():b;if(null===p[a])p[a]={ts:c,state:e,total:0};else{var g=p[a];if(g.state!==e&&!(g.state===t&&e!==x)){var k=c-g.ts,f=g.state;g.ts=c;g.state=e;k<h||(f===x?(g.total+=k,q&&q(c,k)):f===v&&u&&u(c,k))}}}var h=5,k="auto",l="user",n=null,m=null,x=!0,v=!1,t=null;"hidden"in f?(n="hidden",m="visibilitychange"):"mozHidden"in f?(n="mozHidden",m="mozvisibilitychange"):"webkitHidden"in f?(n="webkitHidden",m="webkitvisibilitychange"):
"msHidden"in f&&(n="msHidden",m="msvisibilitychange");var p={};p[k]=null;var q=p[l]=null,u=null;return{support:!!n,auto:function(d,g){q=d||null;u=g||null;n&&(a(),s(f,m,a));oa?(s(e,"pageshow",c),s(e,"pagehide",b)):(s(e,"beforeunload",b),s(e,"unload",b))},set:function(a){g(l,!!a)},getLog:function(){var a=y(),b={},c,d;for(d in p)c=p[d],b[d]=c?c.total:0,c&&c.state&&(b[d]+=a-c.ts);return b},getValue:d}}();ga.auto();var sc={enabled:!1};if(kc){var tc=function(){var a="checkbox color date datetime-local email file month number password radio range search tel text time url week".split(" ");
return{analyze:function(b){if(!b)return null;for(var c=[].slice.apply(b.elements),d=[],e=[],h=0,k=c.length;h<k;h++){var f;a:switch(f=c[h],f.tagName.toLowerCase()){case "button":f=!1;break a;case "input":var l=f.type.toLowerCase();if(l&&-1===a.indexOf(l)){f=!1;break a}default:f=Ib(f,!1)&&f.name&&!1===f.disabled}f&&(d.push(c[h].name),e.push(c[h].type))}return{node:b,inputsName:d.length?d:null,inputsType:e.length?e:null}},getFormByInput:function(a){if(!a)return null;a=a.form||a.getAttribute("form");
return"string"===typeof a?document.getElementById(a)||null:a instanceof HTMLElement?a:null}}}(),sc=function(){function a(a){a=a||e.event;var c=(a.which||a.keyCode)===M;if("which"in a&&a.which===J||"button"in a&&a.button&J||c){a:{a=a.target||a.srcElement;for(var c=0,d=k.length;c<d;c++){var f;b:{f=a;for(var A=k[c],E=0,G=A.types.length;E<G;E++){var r;c:{var q=f;r=A.types[E];var p=null;if(r.filter.tagName)for(var t=0,s=r.filter.tagName.length;t<s&&!(p=Hb(q,r.filter.tagName[t]));t++);else p=q;if(p){if(r.filter.attr)for(q in q=
void 0,r.filter.attr)if(r.filter.attr.hasOwnProperty(q)&&(t=r.filter.attr[q],s=p[q],!0===t&&!s||!1===t&&s||ea(t)&&-1===t.indexOf(s))){r=null;break c}r={source:p,type:r.type,detail:p.tagName}}else r=null}if(r){r.category=A.category;f=r;break b}}f=null}if(f){a=f;break a}}a=null}if(a){if(a.category===g){try{a.data=new URL(a.source.href)}catch(x){}if(!a.data)return}else if(a.category===h){if(a.data=tc.analyze(tc.getFormByInput(a.source)),!a.data)return}else return;c=F;if(c.enabled&&c.modes){d=0;for(f=
c.modes.length;d<f;d++)if(A=a,E=c.modes[d],A.category===E.mode)if(A.category===g||A.category===h){if(E=E.categories,A.data){G=void 0;c:{G=0;for(r=E.length;G<r;G++){for(var p=A,q=E[G],t={category:A.category},s=[],W=0,z=q.types.length;W<z;W++){var sa=q.types[W],C=qa({type:q.category},t),N=v in sa,K;D in sa?K=b(p,sa,C,D):N&&(K=qa({source:p.source,data:p.data,detail:sa.type},C));if(K&&(!N||!b(p,sa,C,v)))if(s.push(K),(sa.rule&u)!==u)break}if(p=s.length?s:null){G=p;break c}}G=null}if(G){A=0;for(E=G.length;A<
E;A++)c:{r=G[A];p={type:"sendEvent",category:"_"+r.category,action:r.detail};if(r.category===g&&(r.type===l||r.type===y)){if(p.label=r.data.href,!p.label)break c}else if(r.category===m&&(p.label=r.data.node.action,!p.label))break c;_tmr.push(p)}}}}else n&&console.warn("[TopMailRu] Error#1.24","Not found tracking for type",A.type)}}}}function b(a,b,d,e){var g=!1,f=b[e];if(ea(f)){var h=b[e+"Rule"]||z;e=(h&t)===t;for(var h=(h&p)===p,k=0,l=f.length;k<l&&!(g=c(a,f[k]),e&&g);k++)if(h&&!g)return null}else g=
c(a,f);return!g?null:qa({source:a.source,data:a.data,detail:b.type},d)}function c(a,b){var c=b.rule||z,e=(c&t)===t,c=(c&p)===p,g=!1,f;for(f in b)if(b.hasOwnProperty(f)&&"rule"!==f){var g=b[f],h;switch(f){case "domain":h=eb(a.data);break;case "fileExtension":h=Jb(a.data.pathname,/.\.([^\.]+)$/,1)||"";break;default:h=a.data[f]}g=!0===g?!!(ea(h)?h.length:h):!1===g?!(ea(h)?h.length:h):d(h,g);if(e&&g)break;else if(c&&!g)return!1}return g}function d(a,b){var c=a;if(c)if(ea(c)){if(!c.length)return!1}else c=
[c];else return!1;var d=b,e=z;if(Z(d)&&!ea(d)){if(!ea(d.value))return!1;e=d.rule||e;d=d.value}a:{for(var g=(e&q)===q,h=(e&t)===t,e=(e&p)===p,f=!1,k=0,l=d.length;k<l;k++){var m=d[k];if(m){var n="string"===typeof m;n&&!g&&(m=m.toLowerCase());var s=m instanceof RegExp;if(n||s){var f=!0,w;b:{w=c;for(var v=g,u=0,y=w.length;u<y;u++){var x=v?w[u]:w[u].toLowerCase();if(s&&m.test(x)||n&&m===x){w=!0;break b}}w=!1}if(h&&w){c=!0;break a}else if(e&&!w){c=!1;break a}}}}c=h?!1:e?f?!0:!1:void 0}return c}var g="click",
h="submit",k=[{category:h,types:[{type:"button",filter:{tagName:["input","button"],attr:{type:["submit","image"]}}}]},{category:g,types:[{type:"a",filter:{tagName:["a"],attr:{href:!0}}}]}],l="file",y="resource",m="submit",D="filter",v="stop",t=1,p=2,q=4,u=8,z=t,F={enabled:!0,modes:[{mode:h,categories:[{category:m,types:[{type:"lead",filter:[{inputsName:["phone"],inputsType:["tel"],rule:t},{inputsName:["email"],inputsType:["email"],rule:t}],filterRule:p,stop:{inputsName:{value:["password"]}}},{type:"form",
filter:{inputsName:!0}}]}]},{mode:g,categories:[{category:"contact",types:[{type:"email",filter:{protocol:["mailto:"]}},{type:"phone",filter:{protocol:["tel:"]}}]},{category:l,types:[{type:"file",filter:{fileExtension:"7z bz2 gz apk iso cab dmg msi rar tar zip exe txt doc docx ppt pptx xls xlsx csv pdf psd rtf ods djvu eps 3gp aac ac3 avi flac flv divx midi mka mkv mp3 mp4 mpeg mpg mov ogg vob wav webm wma wmf wmv torrent".split(" ")}}]},{category:y,types:[{type:"outgoing",rule:u,stop:{domain:[xc(x.host,
3,!1)],href:[/password/]}},{type:"messenger",filter:{domain:fb("vk.me t.me telegram.me telegram.im web.telegram.org m.me web.whatsapp.com api.whatsapp.com chat.whatsapp.com wa.me".split(" "))},stop:{href:[/password/]}},{type:"social",filter:{domain:fb("vk.com vkontakte.ru m.vk.com vk.ru ok.ru m.ok.ru odnoklassniki.ru facebook.com m.facebook.com fb.com twitter.com linkedin.com instagram.com tiktok.com youtube.com youtu.be m.youtube.com".split(" "))},stop:{href:[/password/]}}]}]}]},J=1,M=13;return{enabled:!0,
start:function(){s(f,"click",a);s(f,"keypress",a)}}}();hd&&sc.start()}var z=function(){function a(){b(null)}function b(a){g();a?($=a===W,pa=a):pa=Y&&null!==$?$?W:ba:f.visibilityState;a=B();for(var b in ia)q(b,a)}function c(){if(!1!==T){N(e,Z,ka);ka=null;e.clearInterval(la);ma=la=null;N(f,O,fa);fa=null;Y&&(N(e,U,ga),N(e,aa,ha),ha=ga=null);h(!0);for(var a in ca){var b=a,c=ca[b];c&&(c=c.key,R(b),H(),delete ca[b],A(null,c))}I=null;ja=[];wa=[];L={};ca={};ia={};T=!1}}function d(a,b,c){var d=a+"_"+b;if(d in
L)return!1;var e=y(),g=B(),h=C(d,e,ob);b=L[d]={id:a||null,name:b,key:h,canUseInBackground:!!c,startTS:e,updateTS:g,timespent:{}};if(a)if(wa.push(d),d=b.canUseInBackground,b=ia[a]){if(c=b.isActive,!c&&(e=I&&da(a,I)))if(c=pa===W||d)b.updateTS=g,b.isActive=!0}else e=I&&da(a,I),c=pa===W||d,ia[a]={isActive:e&&c,updateTS:g,timespent:{}};else ja.push(d);return!0}function g(a,b){var c,d;2>arguments.length?(c=wa.concat(ja),d=G):(c=[a+"_"+b],d=E);k(c,d)}function h(a,b,c){var d=!1,e=[],g=[];2>arguments.length?
(e=wa.slice(),(d=!!arguments[0])&&(e=e.concat(ja))):(d=a+"_"+b,-1!==wa.indexOf(d)?e=[d]:-1!==ja.indexOf(d)&&(c?e=[d]:g=[d]));k(e,V);k(g,E)}function k(a,b){var c=B(),d=[],e,g,h;e=0;for(g=a.length;e<g;e++)h=a[e],-1!==wa.indexOf(h)?l(h,b,c):-1!==ja.indexOf(h)&&d.push(h);e=0;for(g=d.length;e<g;e++)h=d[e],l(h,b,c);if(b===G&&(X=c,X-T>=ra)){for(var f in L)m(f);for(f in ca)if(c=f,d=ca[c])R(c),A(c,d.key);T=X}}function l(a,b,c){var d=L[a];if(d&&!1!==d.updateTS)if(d.timespent[pa]=(d.timespent[pa]||0)+(c-(d.updateTS||
X)),-1!==ja.indexOf(a)&&u(null,c),b===V)d.updateTS=!1,m(a);else if(b===r){d.updateTS=c;var e;a:{if(b=L[a])for(e in b.timespent)if(b.timespent[e]>qa){e=!1;break a}e=!0}e?(n(a),H()):m(a)}else d.updateTS=b===G?null:c,n(a),H()}function n(a,b,c){var d=L[a];if(!d)return null;var e=b||d.key;b=S[e];S[e]={uid:a,name:d.name,counterID:c||d.id||I,canUseInBackground:d.canUseInBackground,isActive:!1!==d.updateTS,startTime:d.startTS,timespent:{}};a=S[e].timespent;var d=d.timespent,g;for(g in d)a[g]=d[g];if(c&&(c=
ia[c]))if(e=S[e]){e.common={};e=e.common;c=c.timespent;for(var h in c)e[h]=c[h]}return b||null}function m(a){var b=L[a];b&&(n(a),x(a,b.key))}function x(a,b){var c=S[b];if(c)if(ea(c.counterID)){var d=S[b];if(d){var c=d.counterID,e=[],g,h,f,k;if(c){f=0;for(k=c.length;f<k;f++){h=c[f];g=C(b,h);e.push(g);h=n(a||d.uid,g,h);var l=void 0;h&&(l=S[g],F(l.timespent,h.timespent),h.common&&(l.common=l.common||{},F(l.common,h.common)))}}delete S[b];H();if(a&&a in L)if(d.isActive){t(a);f=0;for(k=c.length;f<k;f++)if(d=
ia[c[f]])for(var m in d.timespent)d.timespent[m]=0}else p(a);f=0;for(k=e.length;f<k;f++)v(e[f])}}else if(m=S[b])(c=a&&a in L)&&!m.isActive&&p(a),e=v(b),c&&(e&&m.isActive)&&t(a)}function v(a){var b;if(b=S[a]){var c=P(b.timespent);if(!1===b.canUseInBackground&&b.isActive&&0===c.fg)b=null;else{c=[b.name,b.startTime,b.canUseInBackground?1:0,c.fg,c.bg];if(b.common){var d=P(b.common);(d.fg||d.bg)&&c.push(d.fg,d.bg)}b={id:b.counterID,msg:c.join("/")}}}else b=!1;if(!b)return!1;c=";e="+escape("TS:"+b.msg);
J(M({id:b.id},K,!1,!1)+c);delete S[a];H();return!0}function t(a){if(a=L[a])for(var b in a.timespent)a.timespent[b]=0}function p(a){if(a in L){var b;-1!==(b=ja.indexOf(a))&&ja.splice(b,1);if(-1!==(b=wa.indexOf(a)))if(wa.splice(b,1),b=L[a].id){var c=ia[b];if(c){var d=c.isActive;d&&D(c,B());d=z(b,a);d||(c.isActive=!1)}}delete L[a]}}function q(a,b){var c=ia[a];if(c){var d=I&&da(a,I),e=z(a);c.isActive=d&&e;c.updateTS=b}}function u(a,b){if(a){var c=ia[a];c&&(c.isActive?D(c,B()):c.updateTS=b)}else for(c in ia)u(c,
b)}function z(a,b){for(var c in L)if(c!==b&&L[c].id===a&&(pa===W||L[c].canUseInBackground))return!0;return!1}function D(a,b){a&&(a.timespent[pa]=(a.timespent[pa]||0)+(b-a.updateTS),a.updateTS=b)}function C(a){return[].join.call(arguments,"_")}function F(a,b){for(var c in b)a[c]=(a[c]||0)+(b[c]||0)}function P(a){var b=a[W]||0,c=0,d;for(d in a)d!==W&&(c+=a[d]);return{fg:b,bg:c}}function B(){return Math.floor(e.performance.now())}function H(){if(na){var a={};a[ua]=S;a[va]=ya;Aa(ta,xa(a)||"")}}function R(a){var b=
ca[a];b&&(ya[b.key]={uid:a,name:b.name,counterID:b.id,value:b.value})}function A(a,b){if(ya[b]){var c;if(c=ya[b])if(0===c.value)c=null;else{var d=[c.name,c.value].join("/");c={id:c.counterID,msg:d}}else c=!1;c&&(d=";e="+escape("TS:"+c.msg),J(M({id:c.id},K,!1,!1)+d));!1!==c&&(delete ya[b],H());if(c&&a&&(c=ca[a]))c.value=0}}var E=1,G=2,r=4,V=8,Z=oa?"pagehide":"unload",O="visibilitychange";"mozHidden"in f?O="mozvisibilitychange":"webkitHidden"in f?O="webkitvisibilitychange":"msHidden"in f&&(O="msvisibilitychange");
var U="focus",aa="blur";"onfocusin"in f&&(U="focusin",aa="focusout");var W="visible",ba="hidden",sa=["0"],Y=!1,qa=100,ra=12E4,T=!1,X=!1,I=null,ja=[],wa=[],L={},pa,$=null,la,ma,fa,ga,ha,ka,ta="tmr_tslog",ua="activity",va="count",S={},ca={},ya={},ia={};return{init:function(){if(na){var a=Ya(za(ta)||"{}");S=a[ua]||{};ya=a[va]||{}}for(var b in S)x(null,b);for(b in ya)A(null,b)},launch:function(){!1===T&&(T=B(),X=B(),pa=Y&&null!==$?$?W:ba:f.visibilityState,ka=c.bind(e),s(e,Z,ka),ma=a.bind(e),la=e.setInterval(ma,
1E4),fa=b.bind(e,null),s(f,O,fa),Y&&(ga=b.bind(e,W),ha=b.bind(e,ba),s(e,U,ga),s(e,aa,ha)))},enable:function(a){if(I){if(da(a,I))return;k(ja,r)}else{for(var b=0,c=sa.length;b<c;b++)d(null,sa[b],!1);I=[]}I.push(a);q(a,B())},disable:function(a){if(I){var b;a:{b=0;for(var c=I.length;b<c;b++)if(I[b]==a)break a;b=-1}if(-1!==b&&(k(ja,r),I.splice(b,1),b=B(),a=ia[a]))a.isActive=!1,a.updateTS=b}},startActivity:d,updateActivity:g,stopActivity:h,incCount:function(a,b){var c=a+"_"+b,d;if(!(d=ca[c]))if(c in ca)d=
ca[c];else{d=y();var e=C(b,d,ob);d=ca[c]={id:a,name:b,key:e,startTS:d,value:0}}d&&d.id===a&&(d.value++,R(c),H())},defaultID:function(){return I?I[0]:void 0}}}(),mb=!1,Fa=null;ec&&function(){function a(){var a=za(e);if(a)try{(a=Ya(a))&&(Fa=a.fpid||null)}catch(b){}c()}function b(){c()}function c(){Aa(d,xa({fpid:Fa,ts:y()}))}var d="tmr_trgfpid",e="rb_sync_id";(function(){var c=na?za(d):null;if(c)try{if(c=Ya(c))if(Fa=c.fpid||null,864E5>y()-c.ts)return}catch(e){}kb("https://privacy-cs.mail.ru/static/sync-loader.js",
a,b)})()}();var Tc="60.5.5",Wa=0,Ia=0,ob=Lb(16),U=null,ra=null,Ha=0,Ca="tmr_reqNum",H=null;ma&&(H=$(Ca)||null,null!==H&&ib(Ca,jb));na&&null===H&&(H=za(Ca)||null);H=null===H?0:parseInt(H,10);na&&Aa(Ca,H);var fa=(ma?$("tmr_lvid"):null)||(na?za("tmr_lvid"):null),Ea=(ma?$("tmr_lvidTS"):null)||(na?za("tmr_lvidTS"):null);if(null===fa||-1===fa.search(/^[0-9a-fA-F]+$/))fa=Lb(32);Pb("tmr_lvid",fa);if(null===Ea||-1===Ea.search(/^\d+$/))Ea=""+y();Pb("tmr_lvidTS",Ea);var aa=0,C=[],Ka=[],bb=[],ab=[],Za=[],Xa=
{},Rc="ontouchstart"in e||1<(B.maxTouchPoints||B.msMaxTouchPoints)?"1":"0",Sc=e.devicePixelRatio||0,Qc=function(){var a=e.screen;return a?a.width+"*"+a.height:""}(),uc=e.performance||e.mozPerformance||e.msPerformance||e.webkitPerformance||{},Qa=uc.timing||{},pb=uc.navigation||{},cc="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),
Ra=Ba("navigationStart"),md=Ba("domContentLoadedEventStart"),nd=Ba("loadEventStart"),Y=Ra,dc="downlink downlinkMax effectiveType rtt saveData type".split(" "),T,Db;T=function(a,b,c){if(b&&"object"===typeof b){var d="id"in b&&b.id||aa,e=c.title||null,f,k=Db(b,{params:c.required,fn:c.fn});if(k.missed.length)console.warn("[TopMailRu]"+(d?"["+d+"]":"")+" Error#1.14","Unspecified "+(1<k.missed.length&&k.missed.slice(0,-1).join(", ")+" and "||"")+k.missed.slice(-1)+" in "+a);else{var l=Db(b,{params:c.optional,
fn:c.fn});f=[].concat(k.values).concat(l.values);k=[].concat(k.missed).concat(l.missed);c.value&&(b="value"in b&&b.value,!0!==c.value&&(b=b||c.value),b?f.push("value: "+b):k.push("value"));c=f.length?"{ "+f.join(", ")+" }":"";f=k.length?"("+(1<k.length?k.slice(0,-1).join(", ")+" and "+k.slice(-1)+" are":k.slice(-1)+" is")+" empty)":"";d?console.info("[TopMailRu]["+d+"]: "+(e||a)+" "+c+" "+f):console.warn("[TopMailRu] Error#1.15","Undefined counter ID of "+a+" "+c)}}else console.warn("[TopMailRu][]["+
a+"] Error#1.13")};Db=function(a,b){var c=[],d=[],e,f,k;if(b.params)for(e in b.params)if(b.params.hasOwnProperty(e)&&!1!==b.params[e])if(f=e in a&&a[e],!0!==b.params[e]&&(f=f||b.params[e]),f)try{k=b.fn?b.fn:null,c.push(e+': "'+(k?k(e,f):f)+'"')}catch(l){console.warn("[TopMailRu] Error#1.16",l)}else d&&d.push(e);return{values:c,missed:d}};var D={},Ua=null,Ta=null,xb=[];l.prototype.callbackOnReady=function(a){n&&T("onReady",a,{title:"OnReady callback"});a&&"object"===typeof a&&"function"===typeof a.callback&&
(a.callback.call(a.context||null),oa&&xb.push(a))};l.prototype.pageView=function(a){va(a);a:if(a&&"object"===typeof a&&a.id){5>Ka.length&&!da(a.id,Ka)&&(Ka.push(a.id),!1!==a.beat&&bb.push(a.id),C.push(a),Ga&&Qb(a));oa&&(Xa[a.id]=qa(!0,{},a),Xa[a.id].bfCache=!0);"detectBlocker"in a&&!a.detectBlocker&&(rb=!0);var b="string"===typeof a.ecommerce,c=b&&-1!==a.ecommerce.search(/\S/);if(5>ab.length&&!da(a.id,ab)&&(!0===a.ecommerce||b&&!c||b&&c||!1!==a.ecommerce&&!b&&(da(a.id,jd)||!da(a.id,kd)))){ab.push(a.id);
if(b&&c){if(zb&&(Ab(a.ecommerce),V!==a.ecommerce)){V=a.ecommerce;P&&(P=[0,0,V]);break a}V=a.ecommerce;P&&(P=[0,0,V])}b=[a.id];if(zb)for(var c=0,d=$a.length;c<d;c++)Rb(b,$a[c])}a.timespent=R&&(a.timespent||da(a.id,gd)&&!1!==a.timespent);R&&(a.timespent?z.enable(a.id):z.disable(a.id));Bb||(Bb=!0===a.geolocation||a.timespent&&!1!==a.geolocation)&&rc(Cb);mb&&!da(a.id,Za)&&(Za.push(a.id),Vb([a.id]))}n&&T("pageView",a,{title:"Page view",optional:{url:x.href}});O(a)&&(J(M(a,"/counter",!1,!0)),Ia=y())};l.prototype.reachGoal=
function(a){va(a);n&&T("reachGoal",a,{title:"Reach goal",value:!0,required:{goal:!0}});if(O(a)&&"goal"in a&&a.goal){var b="value"in a&&a.value?parseInt(a.value)||"":"";J(M(a,K,!1,!0)+(";e="+escape("RG:"+b+"/"+a.goal)))}};var tb="VALUE";l.prototype.itemView=function(a){n&&T("itemView",a,{title:"Item view",optional:{list:!0,pagetype:!0,productid:!0,totalvalue:!0},fn:function(a,b){return(""+b).replace(/;/g," ")}});if(O(a)){var b=a.list||"",c=a.productid||"",d=a.pagetype||"",e=a.totalvalue||0,f=ad(a.id,
d,e,c);f&&this.reachGoal(f);(new Image).src="https://ad.mail.ru/retarget/?counter="+(a.id||aa)+"&list="+b+"&productid="+c+"&pagetype="+d+"&totalvalue="+e+"&_="+Math.random();b="IV:"+e+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");J(M(a,K,!1,!0)+(";e="+escape(b)))}};var bd="vk_ecom_";l.prototype.sendEvent=function(a){va(a);n&&T("sendEvent",a,{title:"Send event",value:!0,required:{category:!0,action:!0},optional:{label:!0},fn:function(a,b){return(""+b).substring(0,
300).replace(/;/g," ")}});if(O(a)&&"category"in a&&a.category&&"action"in a&&a.action){var b=(""+a.category).substring(0,300),c=(""+a.action).substring(0,300),d="label"in a&&a.label?(""+a.label).substring(0,300):"",b="CE:"+("value"in a&&a.value?parseInt(a.value)||"":"")+"/"+(""+b).replace(/;/g," ")+";"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ");J(M(a,K,!1,!0)+(";e="+escape(b)))}};l.prototype.setUserID=function(a){if(null===a||!1===a||void 0===a)this.deleteUserID();else{var b=typeof a;"number"!==
b&&"string"!==b?n&&console.warn("[TopMailRu] Error#1.17","Invalid user ID in setUserID"):(U=a,n&&console.info("[TopMailRu]: Global user ID = "+U))}};l.prototype.getUserID=function(){return U||0===U?U:void 0};l.prototype.deleteUserID=function(){U=null;n&&console.info("[TopMailRu]: Reset global user ID to null")};l.prototype.setUserParams=function(a){if(null===a||!1===a||void 0===a)this.deleteUserParams();else if(Z(a)){try{ra=qa(!0,{},a)}catch(b){n&&console.warn("[TopMailRu] Error#1.22","Invalid user params in setUserParams");
return}n&&console.info("[TopMailRu]: Global user params = "+xa(ra))}else n&&console.warn("[TopMailRu] Error#1.21","Invalid user params in setUserParams")};l.prototype.getUserParams=function(){var a=ra?ra:void 0;return a?qa(!0,{},a):void 0};l.prototype.deleteUserParams=function(){ra=null;n&&console.info("[TopMailRu]: Reset global user params to null")};l.prototype.getClientID=function(){var a=fa;return a||0===a?a:void 0};l.prototype._MT_event=function(a,b,c){va(a);n&&T(b,a,{title:c});O(a)&&J(M(a,K,
!1,!0)+(";e="+escape("MT:/"+b)))};l.prototype.miniAppEvent=function(a){this._MT_event(a,"miniAppEvent","VK Mini App Event")};var Eb=function(a,b){if(R){var c=z.defaultID();O(a,c)&&(!Z(a)||!("activity"in a&&a.activity)?n&&console.warn("[TopMailRu] Error#1.27","Invalid startActivity command: ID of activity is required"):z.startActivity(a.id||c,""+a.activity,null===b?!!a.canUseInBackground:b))}};l.prototype.startTimespent=function(a){Eb(a,null)};l.prototype.startForegroundTimespent=function(a){Eb(a,
!1)};l.prototype.startAnytimeTimespent=function(a){Eb(a,!0)};l.prototype.updateTimespent=function(a){if(R){var b=z.defaultID();O(a,b)&&(!Z(a)||!("activity"in a&&a.activity)?z.updateActivity():"number"===typeof a.activity||"string"===typeof a.activity?z.updateActivity(a.id||b,""+a.activity):n&&console.warn("[TopMailRu] Error#1.28","Invalid updateActivity command: ID of activity should be number or string"))}};l.prototype.stopTimespent=function(a){if(R){var b=z.defaultID();O(a,b)&&(!Z(a)||!("activity"in
a&&a.activity)?z.stopActivity(!1):"number"===typeof a.activity||"string"===typeof a.activity?z.stopActivity(a.id||b,""+a.activity,!1):n&&console.warn("[TopMailRu] Error#1.29","Invalid stopActivity command: ID of activity should be number or string"))}};l.prototype.incrementEventTimespent=function(a){if(R){var b=z.defaultID();O(a,b)&&(!a||!("activity"in a&&a.activity)?n&&console.warn("[TopMailRu] Error#1.31","Invalid incrementEventTimespent command: ID of countable activity is required"):z.incCount(a.id||
b,""+a.activity))}};l.prototype.processEvent=function(a,b){if(a&&"object"===typeof a)if("type"in a){if("onready"===a.type){if(b&&0>b)return;this.callbackOnReady(a)}else if(b&&0<b)return;switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a);break;case "sendEvent":this.sendEvent(a);break;case "setUserID":"userid"in a&&this.setUserID(a.userid);break;case "deleteUserID":this.deleteUserID();break;case "setUserParams":"params"in a&&
this.setUserParams(a.params);break;case "deleteUserParams":this.deleteUserParams();break;case "miniAppEvent":this.miniAppEvent(a);break;case "startTimespent":this.startTimespent(a);break;case "startForegroundTimespent":this.startForegroundTimespent(a);break;case "startAnytimeTimespent":this.startAnytimeTimespent(a);break;case "updateTimespent":this.updateTimespent(a);break;case "stopTimespent":this.stopTimespent(a);break;case "incrementEventTimespent":this.incrementEventTimespent(a)}}else n&&console.warn("[TopMailRu] Error#1.19",
"Unspecified type of push event");else n&&console.warn("[TopMailRu] Error#1.18","Invalid push event")};l.prototype.push=function(a){for(var b=0,c=arguments.length;b<c;b++)this.processEvent(arguments[b])};var vc=!1;l.prototype.onready=function(){vc||(vc=!0,!rb&&!Ga&&id(Uc,Vc),Ab(V),Wc())};var wb=!1;l.prototype.onload=function(){if(!wb){wb=!0;Ha=y();if(!La&&0<C.length){for(var a=";e="+escape("RT/load")+";et="+Ha,b=0;b<C.length;b++)J(M(C[b],K,!0,!0)+a);Ia=Ha}Yc()}};l.prototype.beat=function(){var a;
if(!sb&&Wa){var b=y();if(!(12E4<b-Wa)){if(12E4<b-Ia){a=";e="+escape("RT/resend")+";et="+Ha;for(var c=0;c<C.length;c++)!1!==C[c].beat&&J(M(C[c],K,!1,!0)+a)}else 0<bb.length&&(a=";e="+escape("RT/beat")+";ids="+escape(bb.join()),J(M({id:bb[0]},K,!1,!0)+a));Ia=b}}};var vb=!1;l.prototype.unload=function(){if(!vb){vb=!0;if(!La){var a;a=(a=Wb())?y()-a:void 0;a=";e="+escape("RT/unload")+";et="+y()+(a?";pvt="+escape(a):"");if(ga.support){var b=ga.getLog();a+=";vtauto="+b.auto}for(b=0;b<C.length;b++)J(M(C[b],
K,!0,!0)+a)}oa&&(D.dcl3&&(clearTimeout(D.dcl3),delete D.dcl3),D.pvt2&&(clearTimeout(D.pvt2),delete D.pvt2),D.pvt15&&(clearTimeout(D.pvt15),delete D.pvt15),D.beat&&(clearInterval(D.beat),delete D.beat))}};l.prototype.activity=function(a){Wa=y()};var ka=_tmr;_tmr=new l;R&&z.init();for(var F=0,Na=ka.length,X;F<Na;F++)(X=ka[F])&&"object"===typeof X&&va(X);cb=(new Date).getTime();F=0;for(Na=ka.length;F<Na;F++)X=ka[F],_tmr.processEvent(X,1);Oa=(new Date).getTime();F=0;for(Na=ka.length;F<Na;F++)X=ka[F],
_tmr.processEvent(X,-1);"complete"===f.readyState||"loading"!==f.readyState&&!f.documentElement.doScroll?(Ta=md,_tmr.onready(),jc()):f.addEventListener?s(f,"DOMContentLoaded",Va):f.attachEvent&&s(f,"readystatechange",Va);"complete"===f.readyState?(Ua=nd,_tmr.onload()):oa?s(e,"pageshow",ub):s(e,"load",ub);oa?s(e,"pagehide",Ja):(s(e,"unload",Ja),s(e,"beforeunload",Ja));ic();if(!sb)try{for(var wc="scroll gesturechange touchmove mousedown mousemove mouseup touch".split(" "),od=function(a){s(f,a,function(){_tmr.activity(a)})},
F=0;F<wc.length;F++)od(wc[F]);s(e,"scroll",function(){_tmr.activity("scallback")})}catch(pd){n&&console.warn("[TopMailRu] Error#1.20",pd)}Pa=(new Date).getTime()}})();
